### ISSUE TITLE
Hodi - app.bundle.js not being generated 

### ISSUE THREAD

**Issue by jbraun27** [driftyco/ionic-pwa-demos#4]
Apparently a new version of ionic-gulp-browserify-typescript is halting the compile on a typescript error, but I'm unable to find the error.

**Comment by jgw96** [comment]
Interesting. Mind posting a screenshot of the typescript error you are getting? Thanks!

**Comment by jbraun27** [comment]
unning 'serve:before' gulp task before serve
[13:35:42] Starting 'clean'...
[13:35:42] Finished 'clean' after 50 ms
[13:35:42] Starting 'watch'...
[13:35:42] Starting 'sass'...
[13:35:42] Starting 'html'...
[13:35:42] Starting 'fonts'...
[13:35:42] Starting 'scripts'...
[13:35:42] Finished 'html' after 167 ms
[13:35:42] Finished 'scripts' after 285 ms
[13:35:42] Finished 'fonts' after 291 ms
[13:35:44] Finished 'sass' after 2.14 s
TypeScript error: C:/Dev/Ionic Progressive Web Apps/ionic-pwa-demos/hodi/node_modules/angularfire2/angularfire2.d.ts(4,10): Error TS2305: Module '"C:/Dev/Ionic Progressive Web Apps/ionic-pwa-demos/hodi/node_modules/@angular/core/index"' has no exported member 'ModuleWithProviders'.
TypeScript error: C:/Dev/Ionic Progressive Web Apps/ionic-pwa-demos/hodi/node_modules/angularfire2/auth/auth.d.ts(11,20): Error TS1112: A class member cannot be declared optional.
TypeScript error: C:/Dev/Ionic Progressive Web Apps/ionic-pwa-demos/hodi/node_modules/angularfire2/database/firebase_object_observable.d.ts(6,17): Error TS1112: A class member cannot be declared optional.
[13:35:47] Finished 'watch' after 4.54 s

**Comment by jgw96** [comment]
Would you mind pulling a fresh clone and trying again. Just committed a fix that should solve this. Thanks!

**Comment by jbraun27** [comment]
Great job @jgw96  That worked.  Sorry it took a while, I had to jump into a meeting. 
I might have some more questions about replacing firebase and sandbox.simplewebrtc.com, any additional discussion, reference, docs would be great! Thanks again.

**Comment by jgw96** [comment]
@jbraun27 Thanks! Glad that fixed it for you! I will be working on updating all these demos this week which will include some docs on each.

**Comment by jbraun27** [comment]
Thanks @jgw96  Just a quick note, I got it to work in a browser with ionic serve, but when I added the android platform and uploaded it to ionic view, nothing happens when you press the "Login with Google" button on Android. I don't have a good emulator and debugging facilities for Android yet, so right now, that's all I know. Have you been able to get it to work?

**Comment by jgw96** [comment]
@jbraun27 That is because of a bug with AngularFire that causes login to not work successfully with a cordova app which is what adding the android platform does.

**Comment by jbraun27** [comment]
Hi again @jgw96 Justin, I know this is closed... but can you point me to a resource of how to target to a web server?  I want to host Ionic project  on an Azure WebApp like Hodi running here: https://jgw96.github.io/hodi/www/  I can't run Ionic Serve from a WebApp, so how can I deploy Hodi on a web server?
